[FE] alarm
hwinkr/discord-alram-test pull request #40
Opened 2024-07-30 03:41 UTC by hwinkr

12345

2024-07-30 03:41 UTC, hwinkr reviewed
리뷰

2024-07-30 04:11 UTC, hwinkr commented
comment

2024-07-30 04:12 UTC, hwinkr commented
comment

2024-07-30 04:13 UTC, hwinkr reviewed
review

2024-07-30 04:15 UTC, hwinkr commented
12345

2024-07-30 04:16 UTC, hwinkr commented
review

2024-07-30 04:17 UTC, hwinkr commented
review

2024-07-30 04:20 UTC, hwinkr reviewed
ㄱㄷ

2024-07-30 04:22 UTC, hwinkr commented
12344

2024-07-30 04:23 UTC, hwinkr commented
1

2024-07-31 02:45 UTC, hwinkr reviewed
123

2024-07-31 02:47 UTC, hwinkr reviewed
123

2024-07-31 02:48 UTC, hwinkr reviewed
12345

2024-07-31 02:52 UTC, hwinkr reviewed
12345

2024-07-31 02:53 UTC, hwinkr commented
1234

2024-07-31 03:23 UTC, hwinkr reviewed
123344

2024-07-31 03:26 UTC, hwinkr reviewed
123

2024-07-31 03:29 UTC, hwinkr reviewed
123

2024-07-31 04:12 UTC, hwinkr reviewed
12345

2024-07-31 04:16 UTC, hwinkr reviewed
2345

2024-07-31 04:16 UTC, Yoonkyoungme requested changes
다시 하세요

2024-07-31 04:17 UTC, Yoonkyoungme approved these changes
잘했어요

2024-07-31 04:17 UTC, Yoonkyoungme commented
여기 다는거 안옴?

2024-07-31 04:17 UTC, Yoonkyoungme reviewed
코멘트는 됨?

2024-07-31 04:29 UTC, hwinkr reviewed
comment

2024-07-31 04:29 UTC, merged